parallelism = 2

[graph]
edge_list_csv = "edges-compass.csv.gz"
vertex_list_csv = "vertices-compass.csv.gz"
verbose = true

[traversal]
type = "speed_grade_energy_model"
model_type = "smartcore"
speed_table_path = "edges-posted-speed-enumerated.txt.gz"
energy_model_path = "2016_TOYOTA_Camry_4cyl_2WD.bin"
ideal_energy_rate = 0.02857142857
speed_table_speed_unit = "kilometers_per_hour"
energy_model_speed_unit = "miles_per_hour"
energy_model_grade_unit = "decimal"
energy_model_energy_rate_unit = "gallons_gasoline_per_mile"
output_time_unit = "minutes"
output_distance_unit = "miles"
real_world_energy_adjustment = 1.166 

[plugin]
input_plugins = [
    { type = "grid_search" },
    { type = "vertex_rtree", vertices_file = "vertices-compass.csv.gz" },
]
output_plugins = [
    { type = "summary" },
    { type = "traversal", route = "geo_json", tree = "geo_json", geometry_file = "edges-geometries-enumerated.txt.gz" },
    { type = "uuid", uuid_file = "vertices-uuid-enumerated.txt.gz" },
]
