[package]
name = "compass-tomtom"
version = "0.1.0"
edition = "2021"


[dependencies]
compass-core = { path = "../compass-core" }
csv = { version = "1.2.2" }
serde = { workspace = true, features = ["derive"] }
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "serde"] }