[package]
name = "compass-core"
version = "0.1.0"
edition = "2021"
exclude = ["test/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true, features = ["derive"] }
rayon = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
flate2 = { workspace = true }
anyhow = "1.0.70"
bincode = "1.3.3"
geo = { workspace = true }
rstar = "0.10.0"
uom = { workspace = true, features = ["use_serde"] }
ordered-float = "3.7.0"
smartcore = { version = "0.3.1", features = ["serde"] }
derive_more = "0.99.0"
keyed_priority_queue = "0.4.1"
