name: routee-compass 
channels:
  - defaults
dependencies:
  - python>=3.8
  - sqlalchemy
  - psycopg2
  - geopandas
  - pip
  - pip:
    - --extra-index-url https://github.nrel.gov/pages/MBAP/mbap-pypi/ 
    - polestar
    - routee-powertrain 
    - shapely
    - pyproj
    - .
