[build-system]
requires = ["maturin>=0.15,<0.16"]
build-backend = "maturin"

[project]
name = "nrel.routee.compass"
version = "0.1.3"
description = "An eco-routing tool build upon RouteE-Powertrain"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "National Renewable Energy Laboratory" }]
license = { text = "BSD 3-Clause License Copyright (c) 2022, Alliance for Sustainable Energy, LLC" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering",
]
keywords = ["eco routing"]
dependencies = [
    "pandas",
    "geopandas",
    "sqlalchemy",
    "psycopg2-binary"
]
[project.optional-dependencies]
dev = ["black", "pytest", "maturin"]


[project.urls]
Homepage = "https://github.nrel.gov/MBAP/routee-compass"

[tool.black]
line-length = 100

[tool.maturin]
python-source="python"
features = ["pyo3/extension-module"]
module-name = "nrel.routee.compass.compass_rust"
manifest-path = "rust/Cargo.toml"