[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "nrel.routee.compass"
version = "0.2.0"
description = "An eco-routing tool build upon RouteE-Powertrain"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "National Renewable Energy Laboratory" }]
license = { text = "BSD 3-Clause License Copyright (c) 2022, Alliance for Sustainable Energy, LLC" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering",
]
keywords = ["eco routing"]
dependencies = []
[project.optional-dependencies]
osm = ['osmnx', 'toml']
dev = ["black", "pytest", "maturin"]

[project.urls]
Homepage = "https://github.nrel.gov/MBAP/routee-compass"

[tool.maturin]
python-source = "python"
features = ["pyo3/extension-module"]
module-name = "nrel.routee.compass.compass_app_py"
manifest-path = "rust/compass-app-py/Cargo.toml"
