[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "routee-compass"
version = "0.2.0"
description = ""
authors = ["Nicholas Reinicke <Nicholas.Reinicke@nrel.gov>"]
packages = [
    {include = "compass"}
]

[[tool.poetry.source]]
name = "mbap-pypi"
url = "https://github.nrel.gov/pages/MBAP/mbap-pypi/"

[tool.poetry.dependencies]
python = ">=3.8"
polestar = {version = "0.1.6", source = "mbap-pypi"}
routee-powertrain = {version = "*", source = "mbap-pypi"}

[tool.poetry.dev-dependencies]
pytest = "^3.4"
black = "*"