[build-system]
requires = ["setuptools>=63.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nrel.routee.compass"
version = "0.1.3"
description = "An eco-routing tool build upon RouteE-Powertrain"
readme = "README.md"
authors = [{ name = "National Renewable Energy Laboratory" }]
license = { text = "BSD 3-Clause License Copyright (c) 2022, Alliance for Sustainable Energy, LLC" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering",
]
keywords = ["eco routing"]
dependencies = [
    "routee-powertrain",
    "nrel.mappymatch",
]
requires-python = ">=3.8"


[project.urls]
Homepage = "https://github.nrel.gov/MBAP/routee-compass"

[tool.black]
line-length = 100

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["nrel*"]  # package names should match these glob patterns (["*"] by default)

[tool.setuptools.package-data]
"*" = ["py.typed"]
