query_timeout_ms = 2000

[graph.tomtom]
edge_file = "edges.csv.gz"
vertex_file = "vertices.csv.gz"
verbose = true

[search.algorithm.astar]
heuristic = "haversine"
bidirectional = false

[search.traversal_model.distance]

[plugin]
input_plugins = [{ type = "vertex_rtree", vertices_file = "vertices.csv.gz" }]
output_plugins = []
