query_timeout_ms = 2000

[graph.tomtom]
edge_file = "edges.csv.gz"
vertex_file = "vertices.csv.gz"
verbose = true

[search.algorithm.astar]
heuristic = "haversine"
bidirectional = false

[search.traversal_model]
edge_cost_functions = [
  { type = "distance" },
  { type = "powertrain", model = "random_forest" },
]
edge_edge_cost_functions = []
valid_functions = []
terminate_functions = []
edge_aggregation_function = "add"
edge_edge_aggregation_function = "add"

[plugin]
input_plugins = [{ type = "vertex_rtree", vertices_file = "vertices.csv.gz" }]
output_plugins = []
