[package]
name = "compass_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = {version = "0.18.2", features=["extension-module", "anyhow"]}
serde = {version = "1.0.160", features=["derive"]}
anyhow = "1.0.70"
bincode = "1.3.3"
geo = "0.24.1"
rstar = "0.10.0"
smartcore = { version = "0.3.1", features = ["serde"] }
rayon = "1.7.0"
thiserror = "1.0.0"
derive_more = "0.99.0"

[lib]
name = "compass_rust"
crate-type = ["cdylib"]