[workspace]
members = [
    "compass-core",
    "compass-powertrain",
    "compass-tomtom",
    "compass-app",
    "compass-app-py",
]

[workspace.dependencies]
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0"
rayon = "1.7.0"
geo = "0.26.0"
rstar = "0.11.0"
thiserror = "1.0.0"
flate2 = "1.0"
kdam = "0.4.1"
log = "0.4.19"
env_logger = "0.10.0"
csv = { version = "1.2.2" }
itertools = { version = "0.11.0" }
chrono = "0.4.26"
regex = "1.9.5"
