[workspace]
members = [
    "compass-core",
    "compass-powertrain",
    "compass-tomtom",
    "compass-app",
    "compass-prototype",
]

[workspace.dependencies]
serde = {version = "1.0.160", features=["derive"]}
rayon = "1.7.0"
thiserror = "1.0.0"
flate2 = "1.0"
kdam = "0.3.0"
log = "0.4.19"
env_logger = "0.10.0"
