[workspace]
members = [
    "compass-prototype",
    "compass-core",
    "compass-tomtom"
]

[workspace.dependencies]
serde = {version = "1.0.160", features=["derive"]}
rayon = "1.7.0"
thiserror = "1.0.0"
flate2 = "1.0"