parallelism = 2
search_orientation = "vertex"
response_persistence_policy = "persist_response_in_memory"
[response_output_policy]
type = "no_output"

# # example file output policy
# response_persistence_policy = "discard_response_from_memory"
# [response_output_policy]
# type = "run_batch_file_sink"
# filename = "output.json"
# format = { type = "json", newline_delimited = true }

[graph]
verbose = true

[algorithm]
type = "a*"

[traversal]
type = "distance"
distance_unit = "kilometers"

[cost]
cost_aggregation = "sum"
network_state_variable_rates = {}

[frontier]
type = "no_restriction"

[termination]
type = "query_runtime"
limit = "00:10:00"
frequency = 100_000

[plugin]
input_plugins = []
output_plugins = []
