parallelism = 2
search_orientation = "vertex"

[graph]
verbose = true

[algorithm]
type = "a*"

[traversal]
type = "distance"
distance_unit = "kilometers"

[cost]
cost_aggregation = "sum"
[cost.state_variable_coefficients]
distance = 1
time = 1
[cost.vehicle_state_variable_rates.distance]
type = "factor"
factor = 0.407085 # based on 65.5 cents per mile 2023 IRS mileage rate
[cost.vehicle_state_variable_rates.time]
type = "factor"
factor = 0.0055556 # based on $20/hr 

[frontier]
type = "no_restriction"

[termination]
type = "query_runtime"
limit = "00:02:00"
frequency = 100_000

[plugin]
input_plugins = []
output_plugins = []
