parallelism = 2
search_orientation = "vertex"

[graph]
verbose = true

[algorithm]
type = "a*"

[traversal]
type = "distance"
distance_unit = "kilometers"

[cost]
cost_aggregation = "sum"
network_state_variable_rates = {}

[frontier]
type = "no_restriction"

[termination]
type = "query_runtime"
limit = "00:02:00"
frequency = 100_000

[plugin]
input_plugins = []
output_plugins = []
