query_timeout_ms = 2000

[graph.tomtom]
edge_file = "edges.csv.gz"
vertex_file = "vertices.csv.gz"
verbose = true

[algorithm]
type = "a*"
bidirectional = false

[traversal]
type = "distance"

[frontier]
type = "no_restriction"

[plugin]
input_plugins = [{ type = "vertex_rtree", vertices_file = "vertices.csv.gz" }]
output_plugins = []
