name: deploy-docs

on:
  push:
    branches:
    - main 
    paths:
    - docs/**

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.10" 

    - name: Install dependencies and build book
      shell: bash -el {0}
      working-directory: ${{runner.workspace}}/routee-compass/docs/
      run: |
        conda install rasterio gdal
        pip install ".[dev]"
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html