name: Rust build and test on push + pull request

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: RouteE-Compass Rust Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"

      - name: Setup Rust
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} 
          rustup component add rustfmt

      - name: Build
        working-directory: ./rust
        shell: bash -el {0}
        run: |
          conda install -c conda-forge cxx-compiler 
          cargo build --verbose

      - name: Run tests
        working-directory: ./rust
        run: cargo test --workspace --verbose

      - name: Run formatting
        working-directory: ./rust
        run: cargo fmt --all -- --check
