name: Rust build and test on push + pull request

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  build:
    name: RouteE-Compass Rust Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: |
        rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} 
        rustup component add rustfmt

    - name: Build
      working-directory: ./rust
      run: cargo build --verbose
    
    - name: Run tests
      working-directory: ./rust
      run: cargo test --workspace --verbose

    - name: Run formatting
      working-directory: ./rust
      run: cargo fmt --all -- --check